[package]
name = "kalendar"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
csv = "1.3.1"
fantoccini = "0.22.0"
reqwest = "0.12.22"
serde = "1.0.219"
tokio = {version = "1.46.1", features = ["full"]}
tower-http = {version = "0.6.6", features = ["full"]}
uuid = "1.17.0"
